# Generated by Django 4.2.13 on 2024-08-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SAMLAuthNRequestConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        choices=[
                            ("samlp:AuthnRequest", "samlp:AuthnRequest"),
                            ("saml:Issuer", "saml:Issuer"),
                            ("samlp:NameIDPolicy", "samlp:NameIDPolicy"),
                        ],
                        max_length=256,
                        verbose_name="タグ名",
                    ),
                ),
                ("values", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
