# Generated by Django 4.2.13 on 2024-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saml", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMLIdPConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="IdP 名")),
                ("metadata", models.TextField(verbose_name="SAML メタデータ")),
            ],
        ),
    ]
