# Generated by Django 4.2.13 on 2024-09-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("saml", "0002_samlidpconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlauthnrequestconfiguration",
            name="identity_provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="saml.samlidpconfiguration",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="samlauthnrequestconfiguration",
            name="tag_name",
            field=models.CharField(
                choices=[
                    ("saml2p:AuthnRequest", "samlp:AuthnRequest"),
                    ("saml2p:Issuer", "saml:Issuer"),
                    ("saml2p:NameIDPolicy", "samlp:NameIDPolicy"),
                ],
                max_length=256,
                verbose_name="タグ名",
            ),
        ),
    ]
